spring:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password:
        url: jdbc:mysql://localhost:3306/sailfish
        type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.sailfish.mapper